[package]
name = "ludumdare48"
version = "0.1.0"
authors = ["Alexander <sasha.kudasov04@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geng = "0.7.0-alpha.0"
serde = "1.0.116"
noise = "0.7.0"
